var response2profile = {
	"eop": "You are the kind of walker who wants the ultimate turbo-like walking experience. You want to break a sweat with a few buddies while getting some work done. You are the first to suggest a fast paced walking meeting or brainstorming session.\n\n Do this right now: Email your co-workers to bring their running shoes to the next scheduled meeting. Tell them it’s going to be a fast paced walking meeting. ", 
	"eoe": "You are the kind of walker who wants to get in shape while having a good time. You look around the office and wonder which one of these clowns can break a sweat and crack a joke. Walking is kind of boring unless you’re walking with others and exchanging stories. \n\nDo this right now: Schedule a walking break in your calendar for tomorrow with at least one of your favorite buddies at work. ",
	"eap": "You are the kind of walker who likes to have the flexibility and convenience to break a sweat on your own terms. You also like to get stuff done while you do it. It might mean taking a conference call or catching up with family you haven’t spoken to in a while. \n\nDo this right now: Set calendar reminder for tonight that reminds you to pack your running shoes for work tomorrow.",
	"eae": "You are the kind of walker who likes to have the flexibility and convenience to break a sweat on your own terms. You also like to enjoy yourself while you do it. Walking isn’t that great unless you're listening to a podcast or TED talk. You want to walk and be entertained. \n\nDo this right now: Choose a TED talk right now you haven’t seen, and queue it up for your next walk. ",
	"bop": "You’re the kind of walker who takes a break from the office and bring others along with you. Walking isn’t about getting into shape as much as it is about taking a breather from the machines. Though you’re taking a break from the physical space of the office, you might still want to catch up with colleagues on other things that are related to your work. This might turn your walk into a much needed collective venting session.\n\nDo this right now: Schedule a mindful walking break in your calendar for tomorrow - send the invite to at least one of your colleagues at work. ",
	"boe": "You’re the kind of walker who takes a break from the office and bring others along with you. Walking isn’t about getting into shape as much as it is about taking a breather from the machines. You want this walking break to be as laid back as possible - work is a forbidden topic. Relaxation, jokes, and storytelling are welcome. \n\nDo this right now: Schedule a mindful walking break in your calendar for tomorrow - send the invite to at least one of your colleagues at work. ",
	"bap": "You’re the kind of walker who takes a break from the machines and people in your office - and takes advantage of the solo time. It’s a good time to extricate yourself and get something else done that no one else in the office has to know about - you might bring along your kindle and walk as you read that book on time management. \n\nDo this right now: Choose a book on your kindle/article on your smart device right now to read on your next walk. ",
	"bae": "You’re the kind of walker who takes a break from the machines and people in your office - while relaxing on your own. You might listen to a podcast at a leisurely pace or you might just listen to your surroundings. The point is your walk is just for you: a time to take a break and enjoy.\n\nDo this right now: Decide on a nearby scenic route (garden, trail) for your next walk. If you don’t know any, ask around the office. ",
	"top": "You’re the kind of walker who walks to get to places and likes to do it with other people. Maybe it’s to walk during the day to go get some food or coffee, or maybe it’s to walk between various locations in a city, or buildings on a campus. You also want take the time to get things done while you’re on the go.\n\nDo this right now: Choose a coffee or snack venue that’s a mile or two further than your usual place, schedule a break in your calendar, and send the invite to a co-worker.",
	"toe": "You’re the kind of walker who walks to get to places and likes to do it with other people. Maybe it’s to walk during the day to go get some food or coffee, or maybe it’s to walk between various locations in a city, or buildings on a campus. You also want to have fun while you’re on the go.\n\nDo this right now: Choose a coffee or snack venue that’s a mile or two further than your usual place, schedule a break in your calendar, and send the invite to a co-worker.",
	"tap": "You’re the kind of walker who finds yourself walking to get to places, usually on your own. You want to kill two birds with one stone, and also get some work done you might browse your phone and finish up a few emails, or knock out a phone meeting on the go.\n\nDo this right now: Choose one thing on your to-do list you can get done on your next walking commute. ",
	"tae": "You’re the kind of walker who finds yourself walking to get to places, usually on your own. You’ll take advantage of any commute time to revel in some music, podcast, or audiobook. You just want to enjoy yourself and let go - while on the go.\n\nDo this right now: Choose a book on your kindle/article on your smart device right now to read on your next walking commute. ",
};
